package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_matheuscosta"
)
public class Clientes  implements java.io.Serializable {


     private int idclientes;
     private String nome;
     private String email;
     private String username;
     private String senha;
     private String cpf;
     private Date dataNasc;
     private String endereco;
     private String cidade;
     private String estado;
     private String cep;
     private String descricao;
     private String telefone;
     private int status;
     private int nivel;

    public Clientes() {
    }

	
    public Clientes(int idclientes) {
        this.idclientes = idclientes;
    }
    public Clientes(int idclientes, String nome, String email, String username, String senha, String cpf, Date dataNasc, String endereco, String cidade, String estado, String cep, String descricao, String telefone, int status, int nivel) {
       this.idclientes = idclientes;
       this.nome = nome;
       this.email = email;
       this.username = username;
       this.senha = senha;
       this.cpf = cpf;
       this.dataNasc = dataNasc;
       this.endereco = endereco;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.descricao = descricao;
       this.telefone = telefone;
       this.status = status;
       this.nivel = nivel;
    }
   
     @Id 

    
    @Column(name="idclientes", unique=true, nullable=false)
    public int getIdclientes() {
        return this.idclientes;
    }
    
    public void setIdclientes(int idclientes) {
        this.idclientes = idclientes;
    }

    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="senha", length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="cpf", length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc", length=10)
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }

    
    @Column(name="endereco")
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="cidade", length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="descricao", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="telefone", length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="status")
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="nivel" )
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    @Override
    public String toString(){
    return this.idclientes + "-" + this.nome;
    }
    
    @Override
    public boolean equals(Object object){
    if(object instanceof Clientes){
    Clientes clientes = (Clientes) object;
    if(clientes.getIdclientes()== this.idclientes){
    return true;
    }
    }
    return false;
    }
}


