package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MbcMusica generated by hbm2java
 */
@Entity
@Table(name="mbc_musica"
    ,catalog="db_matheuscosta"
)
public class MbcMusica  implements java.io.Serializable {


     private int mbcIdmusica;
     private String mbcTitulo;
     private String mbcGenero;
     private Date mbcDataLanc;
     private String mbcImagem;
     private String mbcDescricao;
     private int mbcAddAlbum;

    public MbcMusica() {
    }

	
    public MbcMusica(int mbcIdmusica) {
        this.mbcIdmusica = mbcIdmusica;
    }
    public MbcMusica(int mbcIdmusica, String mbcTitulo, String mbcGenero, Date mbcDataLanc, String mbcImagem, String mbcDescricao, int mbcAddAlbum) {
       this.mbcIdmusica = mbcIdmusica;
       this.mbcTitulo = mbcTitulo;
       this.mbcGenero = mbcGenero;
       this.mbcDataLanc = mbcDataLanc;
       this.mbcImagem = mbcImagem;
       this.mbcDescricao = mbcDescricao;
       this.mbcAddAlbum = mbcAddAlbum;
    }
   
     @Id 

    
    @Column(name="mbc_idmusica", unique=true, nullable=false)
    public int getMbcIdmusica() {
        return this.mbcIdmusica;
    }
    
    public void setMbcIdmusica(int mbcIdmusica) {
        this.mbcIdmusica = mbcIdmusica;
    }

    
    @Column(name="mbc_titulo", length=100)
    public String getMbcTitulo() {
        return this.mbcTitulo;
    }
    
    public void setMbcTitulo(String mbcTitulo) {
        this.mbcTitulo = mbcTitulo;
    }

    
    @Column(name="mbc_genero", length=20)
    public String getMbcGenero() {
        return this.mbcGenero;
    }
    
    public void setMbcGenero(String mbcGenero) {
        this.mbcGenero = mbcGenero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mbc_dataLanc", length=10)
    public Date getMbcDataLanc() {
        return this.mbcDataLanc;
    }
    
    public void setMbcDataLanc(Date mbcDataLanc) {
        this.mbcDataLanc = mbcDataLanc;
    }

    
    @Column(name="mbc_imagem", length=100)
    public String getMbcImagem() {
        return this.mbcImagem;
    }
    
    public void setMbcImagem(String mbcImagem) {
        this.mbcImagem = mbcImagem;
    }

    
    @Column(name="mbc_descricao", length=40)
    public String getMbcDescricao() {
        return this.mbcDescricao;
    }
    
    public void setMbcDescricao(String mbcDescricao) {
        this.mbcDescricao = mbcDescricao;
    }

    
    @Column(name="mbc_addAlbum")
    public Integer getMbcAddAlbum() {
        return this.mbcAddAlbum;
    }
    
    public void setMbcAddAlbum(int mbcAddAlbum) {
        this.mbcAddAlbum = mbcAddAlbum;
    }




}


