package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="db_matheuscosta"
)
public class Produtos  implements java.io.Serializable {


     private int idprodutos;
     private int idfornecedores;
     private int idalbum;
     private Date dataPedido;
     private int quantidade;
     private double valorTotal;
     private String status;

    public Produtos() {
    }

	
    public Produtos(int idprodutos) {
        this.idprodutos = idprodutos;
    }
    public Produtos(int idprodutos, int idfornecedores, int idalbum, Date dataPedido, int quantidade, double valorTotal, String status) {
       this.idprodutos = idprodutos;
       this.idfornecedores = idfornecedores;
       this.idalbum = idalbum;
       this.dataPedido = dataPedido;
       this.quantidade = quantidade;
       this.valorTotal = valorTotal;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="idprodutos", unique=true, nullable=false)
    public int getIdprodutos() {
        return this.idprodutos;
    }
    
    public void setIdprodutos(int idprodutos) {
        this.idprodutos = idprodutos;
    }

    
    @Column(name="idfornecedores")
    public int getIdfornecedores() {
        return this.idfornecedores;
    }
    
    public void setIdfornecedores(int idfornecedores) {
        this.idfornecedores = idfornecedores;
    }

    
    @Column(name="idalbum")
    public int getIdalbum() {
        return this.idalbum;
    }
    
    public void setIdalbum(int idalbum) {
        this.idalbum = idalbum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_pedido", length=19)
    public Date getDataPedido() {
        return this.dataPedido;
    }
    
    public void setDataPedido(Date dataPedido) {
        this.dataPedido = dataPedido;
    }

    
    @Column(name="quantidade")
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_total", precision=10)
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="status", length=16)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


