package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="db_matheuscosta"
)
public class Usuarios  implements java.io.Serializable {


     private int idusuarios;
     private String nome;
     private String email;
     private String senha;
     private String telefone;
     private String endereco;
     private String cidade;
     private String estado;
     private String cep;
     private String cnpj;
     private Date dataCadastro;
     private String descricao;
     private int status;
     private int tipoFornecedor;

    public Usuarios() {
    }

	
    public Usuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }
    public Usuarios(int idusuarios, String nome, String email, String senha, String telefone, String endereco, String cidade, String estado, String cep, String cnpj, Date dataCadastro, String descricao, int status, int tipoFornecedor) {
       this.idusuarios = idusuarios;
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.telefone = telefone;
       this.endereco = endereco;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.cnpj = cnpj;
       this.dataCadastro = dataCadastro;
       this.descricao = descricao;
       this.status = status;
       this.tipoFornecedor = tipoFornecedor;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idusuarios")
    public int getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="senha", length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="telefone", length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="endereco")
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="cidade", length=50)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="cnpj", length=14)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCadastro", length=10)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="descricao", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="status")
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    
    @Column(name="tipoFornecedor")
    public int getTipoFornecedor() {
        return this.tipoFornecedor;
    }
    
    public void setTipoFornecedor(int tipoFornecedor) {
        this.tipoFornecedor = tipoFornecedor;
    }
}


