package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VendasProdutos generated by hbm2java
 */
@Entity
@Table(name="vendas_produtos"
    ,catalog="db_matheuscosta"
)
public class VendasProdutos  implements java.io.Serializable {


     private VendasProdutosId id;

    public VendasProdutos() {
    }

    public VendasProdutos(VendasProdutosId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idvendas", column=@Column(name="idvendas", nullable=false) ), 
        @AttributeOverride(name="idprodutos", column=@Column(name="idprodutos", nullable=false) ) } )
    public VendasProdutosId getId() {
        return this.id;
    }
    
    public void setId(VendasProdutosId id) {
        this.id = id;
    }




}


