package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendasProdutosId generated by hbm2java
 */
@Embeddable
public class VendasProdutosId  implements java.io.Serializable {


     private int idvendas;
     private int idprodutos;

    public VendasProdutosId() {
    }

    public VendasProdutosId(int idvendas, int idprodutos) {
       this.idvendas = idvendas;
       this.idprodutos = idprodutos;
    }
   


    @Column(name="idvendas", nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }


    @Column(name="idprodutos", nullable=false)
    public int getIdprodutos() {
        return this.idprodutos;
    }
    
    public void setIdprodutos(int idprodutos) {
        this.idprodutos = idprodutos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendasProdutosId) ) return false;
		 VendasProdutosId castOther = ( VendasProdutosId ) other; 
         
		 return (this.getIdvendas()==castOther.getIdvendas())
 && (this.getIdprodutos()==castOther.getIdprodutos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvendas();
         result = 37 * result + this.getIdprodutos();
         return result;
   }   


}


